$schema: "https://moonrepo.dev/schemas/tasks.json"

fileGroups:
  next:
    - "app/**/*"
    - "pages/**/*"
    - "public/**/*"
    - "src/**/*"
    - "next-env.d.ts"
    - "next.config.*"
  sources: []
  tests:
    - "tests/**/*"

tasks:
  # Catch-all for any `next` command
  next:
    command: "pnpm next"
    local: true

  # Build the application
  build:
    command: "pnpm next build"
    inputs:
      - "@group(next)"
      - "@group(sources)"
    outputs:
      - ".next"

  # Run the development server
  dev:
    command: "pnpm next dev"
    local: true

  # Serve the built application
  start:
    command: "pnpm next start"
    deps:
      - "build"
    local: true
